# hf 
dataset_ckpt: openbmb/Ultra-FineWeb
dataset_split: en
text_column: content
stream_dataset: true
tokenizer_ckpt: HuggingFaceTB/SmolLM-1.7B

save_ckpt: model_ckpts
pretrain_ckpt: ~
enable_liger_kernel: false # true

hf_bucket_name: Jumpr/67
hf_bucket_save_dir: github-actions/test-run-ckpts # model_ckpts/data_ablations/ufineweb-0.5

# wandb + lightning callback
wandb_run_name: github-actions-test-run #ufw-0.5
wandb_run_project: github-actions-testing-project #ufw-quality-ablation-runs
save_every_n_train_steps: 5 #1000
save_top_k: -1
log_every_n_steps: 1 # 10

# lightning trainer parameters
precision: bf16-mixed
gradient_clip_val: 1.0
devices: 1

# training hyperparameters 
batch_size: 1 # 12
batch_acc: 1
lr: 2.5e-4
iterations: 10 #50000
max_epochs: 1
num_workers: 1 #4

# model parameters
seq_len: 1 #2048
embed_dims: 4 #1024
head_size: 4 #64
num_heads: 1 #16
block_num: 1 #16
tie_weights: true
vocab_size: 49152
