# hf 
dataset_ckpt: HuggingFaceFW/fineweb-edu
stream_dataset: false
tokenizer_ckpt: HuggingFaceTB/SmolLM-1.7B

save_ckpt: model_ckpts
pretrain_ckpt: ~
enable_liger_kernel: true

hf_bucket_name: Jumpr/67
hf_bucket_save_dir: colab_test/model_ckpts

# wandb + lightning callback
wandb_run_name: 
wandb_run_project:
save_every_n_train_steps: 250
save_top_k: -1
log_every_n_steps: 10

# lightning trainer parameters
precision: bf16-mixed
gradient_clip_val: 1.0
devices: 1

# training hyperparameters 
batch_size: 128
batch_acc: 1
lr: 3e-4
iterations: 20000
max_epochs: 1
num_workers: 4

# model parameters
seq_len: 2048
embed_dims: 1024
head_size: 64
num_heads: 16
block_num: 16
vocab_size: 49152
